name: 🛡️ GitHub Actions Security Scan

on:
  push:
    paths:
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'

permissions: {}

jobs:
  zizmor-scan:
    name: 🛡️ Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Run Actions Security Scan
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa
        with:
          advanced-security: false
