name: 🛡️ GitHub Actions Security Scan

on:
  push:
    paths:
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - '.github/workflows/*.yml'

permissions: {}

jobs:
  zizmor-scan:
    name: 🛡️ Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          persist-credentials: false

      - name: Run Actions Security Scan
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d
        with:
          advanced-security: false
