name: MyPy

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'

jobs:
  test:
    name: MyPy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[mypy]

      - name: Run tests
        run: |
          mypy tests
          pip uninstall -y C41811.Config
          mypy src
