
name: Test Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test-pypi-publish:
    name: publish to test PyPI
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/C41811.Config/
    permissions:
      id-token: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-package
        path: dist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        repository_url: https://test.pypi.org/legacy/