name: 🚀 Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    name: 📦 Build
    uses: ./.github/workflows/python-build.yml
    permissions:
      id-token: write
      contents: write

  test-pypi-publish:
    name: 🧪 Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/C41811.Config/
    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v5
        with:
          name: python-package-raw
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@d417ba7e7683fa9104c42abe611c1f2c93c0727d
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true

  pypi-publish:
    name: 🚀 Publish to PyPI
    runs-on: ubuntu-latest
    needs: test-pypi-publish
    if: github.event_name == 'release' && github.event.action == 'published'

    environment:
      name: pypi
      url: https://pypi.org/p/C41811.Config/
    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v5
        with:
          name: python-package-raw
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@d417ba7e7683fa9104c42abe611c1f2c93c0727d
        with:
          verbose: true
