
name: Test Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test-pypi-publish:
    name: publish to test PyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/C41811.Config/
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download python package
        uses: actions/cache@v4
        with:
          path: ./dist
          key: python-package-${{ hashFiles('./src/**') }}-${{ hashFiles('./pyproject.toml') }}
          fail-on-cache-miss: true

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          repository_url: https://test.pypi.org/legacy/