name: Test Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    name: Build Python Package
    uses: ./.github/workflows/python-build.yml
    permissions:
      id-token: write
      contents: write

  test-pypi-publish:
    name: publish to test PyPI
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/C41811.Config/
    permissions:
      id-token: write

    steps:
      - name: Download Package
        uses: actions/download-artifact@v4
        with:
          name: python-package-raw
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@916e57631f04a497e4bec0e29e80684e45b4305e
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
