name: Flake8

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[flake8]

      - name: Run tests
        run: >
          flake8
          --doctests --max-line-length=120 --max-complexity=15 --show-source
          --count --statistics
          tests src
