name: MyPy

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - '.github/workflows/python-*.yml'
  pull_request:
    paths:
      - '**.py'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - '.github/workflows/python-*.yml'

jobs:
  test:
    name: MyPy
    runs-on: ubuntu-latest

    permissions:
      contents: read  # for setup-python

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[mypy]

      - name: Run tests
        run: |
          mypy tests
          pip uninstall -y C41811.Config
          mypy src
