name: Flake8

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - '.github/workflows/python-*.yml'
  pull_request:
    paths:
      - '**.py'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - '.github/workflows/python-*.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[flake8]

      - name: Run tests
        run: >
          flake8
          --doctests --max-line-length=120 --max-complexity=10 --show-source
          --count --statistics
          tests src
