name: Flake8

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - '.github/workflows/python-*.yml'
  pull_request:
    paths:
      - '**.py'
      - 'MANIFEST.in'
      - 'pyproject.toml'
      - '.github/workflows/python-*.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read  # for setup-python

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[flake8]

      - name: Run tests
        # todo use ruff instead
        run: >
          flake8
          --doctests --max-line-length=120 --max-complexity=10 --show-source
          --count --statistics --ignore=E122,E121,E126,W503,E123,E704,F401,E701,E203
          tests src
