name: 📝 Spell Check

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  codespell:
    name: 📝 Run Codespell
    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Run Codespell
        uses: codespell-project/actions-codespell@3c04c03694eb927ff908b8b5abfe9c58b239b0ae
