name: 📝 Spell Check

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  codespell:
    name: 📝 Run Codespell
    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run Codespell
        uses: codespell-project/actions-codespell@3abb875e3aa9713e40eed5aea082672a42f7f95c
