name: 📝 Spell Check

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  codespell:
    name: 📝 Run Codespell
    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run Codespell
        uses: codespell-project/actions-codespell@cf810cf4cbd6cdefe6ef86e55b64d524a16654a7
