name: ♻️ Sync To Gitee

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  delete:
    branches: [ main, develop ]
  create:
    branches: [ main, develop ]

jobs:
  build:
    name: ♻️ Sync
    runs-on: ubuntu-latest
    environment:
      name: sync-gitee
    permissions: {}
    steps:
      - name: Sync to Gitee
        # noinspection SpellCheckingInspection
        uses: wearerequired/git-mirror-action@c44c68aebe42de49a80a8dfd557416b6a0cafdad
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:C418-11/C41811_Config.git"
          destination-repo: "git@gitee.com:C418-11/C41811_Config.git"
