name: Sync To Gitee

on:
  push:
    branches: [ main, develop ]
  delete:
    branches: [ main, develop ]
  create:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: sync-gitee
    steps:
      - name: Sync to Gitee
        # noinspection SpellCheckingInspection
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:C418-11/C41811_Config.git"
          destination-repo: "git@gitee.com:C418-11/C41811_Config.git"
