name: ♻️ Sync To Gitee

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  delete:
    branches: [ main, develop ]
  create:
    branches: [ main, develop ]

jobs:
  build:
    name: ♻️ Sync
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'pre-commit-ci[bot]'
    environment:
      name: sync-gitee
    permissions: {}
    steps:
      - name: Sync to Gitee
        # noinspection SpellCheckingInspection
        uses: wearerequired/git-mirror-action@fda53368ae45b56c0430f8d419015a1836b5cfe0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:C418-11/C41811_Config.git"
          destination-repo: "git@gitee.com:C418-11/C41811_Config.git"
